/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.system;

import design.panelTransparant;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author CALAK
 */
public class help_help extends javax.swing.JInternalFrame {
    
    
    public help_help() {
        initComponents();
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        background31 = new design.background3();
        panelTransparant1 = new design.panelTransparant();
        panel1 = new design.panelTransparant();
        panelTransparant4 = new design.panelTransparant();
        button1 = new design.button();
        jLabel1 = new javax.swing.JLabel();
        panelTransparant20 = new design.panelTransparant();
        button2 = new design.button();
        jLabel2 = new javax.swing.JLabel();
        panelTransparant21 = new design.panelTransparant();
        button21 = new design.button();
        jLabel3 = new javax.swing.JLabel();
        panelTransparant22 = new design.panelTransparant();
        button23 = new design.button();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelTransparant23 = new design.panelTransparant();
        button25 = new design.button();
        jLabel6 = new javax.swing.JLabel();
        panelTransparant24 = new design.panelTransparant();
        button27 = new design.button();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelTransparant25 = new design.panelTransparant();
        button29 = new design.button();
        jLabel8 = new javax.swing.JLabel();
        panelTransparant26 = new design.panelTransparant();
        button31 = new design.button();
        jLabel9 = new javax.swing.JLabel();
        panelTransparant27 = new design.panelTransparant();
        button33 = new design.button();
        jLabel10 = new javax.swing.JLabel();
        panelTransparant28 = new design.panelTransparant();
        button35 = new design.button();
        jLabel11 = new javax.swing.JLabel();
        panelTransparant29 = new design.panelTransparant();
        button37 = new design.button();
        jLabel12 = new javax.swing.JLabel();
        panelTransparant30 = new design.panelTransparant();
        button39 = new design.button();
        jLabel13 = new javax.swing.JLabel();
        panelTransparant31 = new design.panelTransparant();
        button41 = new design.button();
        jLabel14 = new javax.swing.JLabel();
        panelTransparant32 = new design.panelTransparant();
        button43 = new design.button();
        jLabel15 = new javax.swing.JLabel();
        panelTransparant33 = new design.panelTransparant();
        button45 = new design.button();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panelTransparant34 = new design.panelTransparant();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        foto1 = new design.foto();
        jLabel25 = new javax.swing.JLabel();
        foto2 = new design.foto();
        foto3 = new design.foto();
        panelTransparant3 = new design.panelTransparant();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        button3 = new design.button();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setEnabled(false);
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1090, 535));

        panel1.setLayout(new java.awt.CardLayout());

        panelTransparant4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button1.setText("Logout");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tombol ini di gunakan untuk keluar dari user yang sedang di gunakan.");

        javax.swing.GroupLayout panelTransparant4Layout = new javax.swing.GroupLayout(panelTransparant4);
        panelTransparant4.setLayout(panelTransparant4Layout);
        panelTransparant4Layout.setHorizontalGroup(
            panelTransparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant4Layout.setVerticalGroup(
            panelTransparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant4, "card2");

        panelTransparant20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button2.setText("Exit");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tombol ini di gunakan untuk keluar dari Program.");

        javax.swing.GroupLayout panelTransparant20Layout = new javax.swing.GroupLayout(panelTransparant20);
        panelTransparant20.setLayout(panelTransparant20Layout);
        panelTransparant20Layout.setHorizontalGroup(
            panelTransparant20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant20Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant20Layout.setVerticalGroup(
            panelTransparant20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant20Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant20, "card2");

        panelTransparant21.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button21.setText("Input Barang");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tombol ini di gunakan untuk memasukan barang yang sudah ada sebelumnya.");

        javax.swing.GroupLayout panelTransparant21Layout = new javax.swing.GroupLayout(panelTransparant21);
        panelTransparant21.setLayout(panelTransparant21Layout);
        panelTransparant21Layout.setHorizontalGroup(
            panelTransparant21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant21Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant21Layout.setVerticalGroup(
            panelTransparant21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant21Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(button21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant21, "card2");

        panelTransparant22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button23.setText("Data Barang");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tombol ini di gunakan untuk menampilkan data barang yang telah di masukan");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("sebelumnya.");

        javax.swing.GroupLayout panelTransparant22Layout = new javax.swing.GroupLayout(panelTransparant22);
        panelTransparant22.setLayout(panelTransparant22Layout);
        panelTransparant22Layout.setHorizontalGroup(
            panelTransparant22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant22Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTransparant22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant22Layout.setVerticalGroup(
            panelTransparant22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant22Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant22, "card2");

        panelTransparant23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button25.setText("Input Suplier");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tombol ini di gunakan untuk memasukan data suplier.");

        javax.swing.GroupLayout panelTransparant23Layout = new javax.swing.GroupLayout(panelTransparant23);
        panelTransparant23.setLayout(panelTransparant23Layout);
        panelTransparant23Layout.setHorizontalGroup(
            panelTransparant23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant23Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant23Layout.setVerticalGroup(
            panelTransparant23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant23Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(button25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant23, "card2");

        panelTransparant24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button27.setText("Data Suplier");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tombol ini di gunakan untuk menampilkan data suplier yang telah di masukan");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("sebelumnya.");

        javax.swing.GroupLayout panelTransparant24Layout = new javax.swing.GroupLayout(panelTransparant24);
        panelTransparant24.setLayout(panelTransparant24Layout);
        panelTransparant24Layout.setHorizontalGroup(
            panelTransparant24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant24Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelTransparant24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant24Layout.setVerticalGroup(
            panelTransparant24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant24Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(button27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant24, "card2");

        panelTransparant25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button29.setText("Input Cabang");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tombol ini di gunakan untuk memasukan data cabang prusahaan.");

        javax.swing.GroupLayout panelTransparant25Layout = new javax.swing.GroupLayout(panelTransparant25);
        panelTransparant25.setLayout(panelTransparant25Layout);
        panelTransparant25Layout.setHorizontalGroup(
            panelTransparant25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant25Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant25Layout.setVerticalGroup(
            panelTransparant25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant25Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(button29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant25, "card2");

        panelTransparant26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button31.setText("Data Cabang");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tombol ini di gunakan untuk melihat data cabang prusahaan yang ada.");

        javax.swing.GroupLayout panelTransparant26Layout = new javax.swing.GroupLayout(panelTransparant26);
        panelTransparant26.setLayout(panelTransparant26Layout);
        panelTransparant26Layout.setHorizontalGroup(
            panelTransparant26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant26Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant26Layout.setVerticalGroup(
            panelTransparant26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant26Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(button31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant26, "card2");

        panelTransparant27.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button33.setText("Input Barang Masuk");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Tombol ini di gunakan untuk memasukan data barang yang baru di beli.");

        javax.swing.GroupLayout panelTransparant27Layout = new javax.swing.GroupLayout(panelTransparant27);
        panelTransparant27.setLayout(panelTransparant27Layout);
        panelTransparant27Layout.setHorizontalGroup(
            panelTransparant27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant27Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant27Layout.setVerticalGroup(
            panelTransparant27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant27Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(button33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant27, "card2");

        panelTransparant28.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button35.setText("Data Barang Masuk");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Tombol ini di gunakan untuk keluar meliahat data barang yang baru masuk.");

        javax.swing.GroupLayout panelTransparant28Layout = new javax.swing.GroupLayout(panelTransparant28);
        panelTransparant28.setLayout(panelTransparant28Layout);
        panelTransparant28Layout.setHorizontalGroup(
            panelTransparant28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant28Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant28Layout.setVerticalGroup(
            panelTransparant28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant28Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(button35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant28, "card2");

        panelTransparant29.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button37.setText("Input Barang Keluar");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tombol ini di gunakan untuk memasukan data barang yang ingin di keluarkan.");

        javax.swing.GroupLayout panelTransparant29Layout = new javax.swing.GroupLayout(panelTransparant29);
        panelTransparant29.setLayout(panelTransparant29Layout);
        panelTransparant29Layout.setHorizontalGroup(
            panelTransparant29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant29Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant29Layout.setVerticalGroup(
            panelTransparant29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant29Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(button37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant29, "card2");

        panelTransparant30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button39.setText("Data Barang Keluar");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Tombol ini di gunakan untuk melihat data barang yang telah dikeluarkan.");

        javax.swing.GroupLayout panelTransparant30Layout = new javax.swing.GroupLayout(panelTransparant30);
        panelTransparant30.setLayout(panelTransparant30Layout);
        panelTransparant30Layout.setHorizontalGroup(
            panelTransparant30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant30Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant30Layout.setVerticalGroup(
            panelTransparant30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant30Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(button39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant30, "card2");

        panelTransparant31.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button41.setText("Retur Barang");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Tombol ini di gunakan untuk mendata barang yang akan di retur/dikembalikan.");

        javax.swing.GroupLayout panelTransparant31Layout = new javax.swing.GroupLayout(panelTransparant31);
        panelTransparant31.setLayout(panelTransparant31Layout);
        panelTransparant31Layout.setHorizontalGroup(
            panelTransparant31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant31Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant31Layout.setVerticalGroup(
            panelTransparant31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant31Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(button41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant31, "card2");

        panelTransparant32.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button43.setText("Input User");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Tombol ini di gunakan untuk menambah pengguna program ini.");

        javax.swing.GroupLayout panelTransparant32Layout = new javax.swing.GroupLayout(panelTransparant32);
        panelTransparant32.setLayout(panelTransparant32Layout);
        panelTransparant32Layout.setHorizontalGroup(
            panelTransparant32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant32Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant32Layout.setVerticalGroup(
            panelTransparant32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant32Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(button43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant32, "card2");

        panelTransparant33.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        button45.setText("Hak Akses");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Tombol ini di gunakan untuk mengatur hak akses apa saja yang boleh digunakan");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("oleh user yang ada.");

        javax.swing.GroupLayout panelTransparant33Layout = new javax.swing.GroupLayout(panelTransparant33);
        panelTransparant33.setLayout(panelTransparant33Layout);
        panelTransparant33Layout.setHorizontalGroup(
            panelTransparant33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant33Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(button45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelTransparant33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparant33Layout.setVerticalGroup(
            panelTransparant33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant33Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelTransparant33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(button45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant33, "card2");

        panelTransparant34.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simple Presentation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N
        panelTransparant34.setPreferredSize(new java.awt.Dimension(776, 443));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Jika ada keluhan anda dapat menghubungi kami di :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Telepon :");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Email     :");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("089650077988");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Jemmy.sapta14@gmail.com");

        javax.swing.GroupLayout foto1Layout = new javax.swing.GroupLayout(foto1);
        foto1.setLayout(foto1Layout);
        foto1Layout.setHorizontalGroup(
            foto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        foto1Layout.setVerticalGroup(
            foto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Jemmy Calak");

        javax.swing.GroupLayout foto2Layout = new javax.swing.GroupLayout(foto2);
        foto2.setLayout(foto2Layout);
        foto2Layout.setHorizontalGroup(
            foto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        foto2Layout.setVerticalGroup(
            foto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout foto3Layout = new javax.swing.GroupLayout(foto3);
        foto3.setLayout(foto3Layout);
        foto3Layout.setHorizontalGroup(
            foto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );
        foto3Layout.setVerticalGroup(
            foto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelTransparant34Layout = new javax.swing.GroupLayout(panelTransparant34);
        panelTransparant34.setLayout(panelTransparant34Layout);
        panelTransparant34Layout.setHorizontalGroup(
            panelTransparant34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant34Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panelTransparant34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTransparant34Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24))
                    .addGroup(panelTransparant34Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23))
                    .addComponent(jLabel17)
                    .addGroup(panelTransparant34Layout.createSequentialGroup()
                        .addComponent(foto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(foto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparant34Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(144, 144, 144))
        );
        panelTransparant34Layout.setVerticalGroup(
            panelTransparant34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant34Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panelTransparant34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparant34Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addGroup(panelTransparant34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(panelTransparant34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)))
                    .addComponent(foto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addGap(99, 99, 99)
                .addGroup(panelTransparant34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        panel1.add(panelTransparant34, "card2");

        panelTransparant3.setBorder(javax.swing.BorderFactory.createTitledBorder("Help"));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Logout");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Exit");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Input Barang");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Data Barang");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Input Suplier");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Data Suplier");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Input Cabang");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("Data Cabang");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("Input Barang Masuk");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("Data Barang Masuk");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setText("Input Barang Keluar");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setText("Data Barang Keluar");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setText("Retur Barang");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setText("Input User");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setText("Hak Akses");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton16);
        jRadioButton16.setText("Contack");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransparant3Layout = new javax.swing.GroupLayout(panelTransparant3);
        panelTransparant3.setLayout(panelTransparant3Layout);
        panelTransparant3Layout.setHorizontalGroup(
            panelTransparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelTransparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton16)
                    .addGroup(panelTransparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRadioButton15)
                        .addComponent(jRadioButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        panelTransparant3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButton1, jRadioButton10, jRadioButton11, jRadioButton12, jRadioButton13, jRadioButton14, jRadioButton15, jRadioButton16, jRadioButton2, jRadioButton3, jRadioButton4, jRadioButton5, jRadioButton6, jRadioButton7, jRadioButton8, jRadioButton9});

        panelTransparant3Layout.setVerticalGroup(
            panelTransparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant3Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/exit.png"))); // NOI18N
        button3.setText("Keluar");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransparant1Layout = new javax.swing.GroupLayout(panelTransparant1);
        panelTransparant1.setLayout(panelTransparant1Layout);
        panelTransparant1Layout.setHorizontalGroup(
            panelTransparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant1Layout.createSequentialGroup()
                .addGroup(panelTransparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparant1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelTransparant3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelTransparant1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTransparant1Layout.setVerticalGroup(
            panelTransparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparant1Layout.createSequentialGroup()
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTransparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTransparant3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout background31Layout = new javax.swing.GroupLayout(background31);
        background31.setLayout(background31Layout);
        background31Layout.setHorizontalGroup(
            background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparant1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        background31Layout.setVerticalGroup(
            background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparant1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(true);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        panelTransparant20.setVisible(true);
        panelTransparant4.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(true);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(true);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(true);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(true);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(true);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(true);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(true);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(true);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(true);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(true);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(true);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(true);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(true);
        panelTransparant34.setVisible(false);
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
        panelTransparant4.setVisible(false);
        panelTransparant20.setVisible(false);
        panelTransparant21.setVisible(false);
        panelTransparant22.setVisible(false);
        panelTransparant23.setVisible(false);
        panelTransparant24.setVisible(false);
        panelTransparant25.setVisible(false);
        panelTransparant26.setVisible(false);
        panelTransparant27.setVisible(false);
        panelTransparant28.setVisible(false);
        panelTransparant29.setVisible(false);
        panelTransparant30.setVisible(false);
        panelTransparant31.setVisible(false);
        panelTransparant32.setVisible(false);
        panelTransparant33.setVisible(false);
        panelTransparant34.setVisible(true);
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_button3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private design.background3 background31;
    private design.button button1;
    private design.button button2;
    private design.button button21;
    private design.button button23;
    private design.button button25;
    private design.button button27;
    private design.button button29;
    private design.button button3;
    private design.button button31;
    private design.button button33;
    private design.button button35;
    private design.button button37;
    private design.button button39;
    private design.button button41;
    private design.button button43;
    private design.button button45;
    private javax.swing.ButtonGroup buttonGroup1;
    private design.foto foto1;
    private design.foto foto2;
    private design.foto foto3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private design.panelTransparant panel1;
    private design.panelTransparant panelTransparant1;
    private design.panelTransparant panelTransparant20;
    private design.panelTransparant panelTransparant21;
    private design.panelTransparant panelTransparant22;
    private design.panelTransparant panelTransparant23;
    private design.panelTransparant panelTransparant24;
    private design.panelTransparant panelTransparant25;
    private design.panelTransparant panelTransparant26;
    private design.panelTransparant panelTransparant27;
    private design.panelTransparant panelTransparant28;
    private design.panelTransparant panelTransparant29;
    private design.panelTransparant panelTransparant3;
    private design.panelTransparant panelTransparant30;
    private design.panelTransparant panelTransparant31;
    private design.panelTransparant panelTransparant32;
    private design.panelTransparant panelTransparant33;
    private design.panelTransparant panelTransparant34;
    private design.panelTransparant panelTransparant4;
    // End of variables declaration//GEN-END:variables
}
